on:
  workflow_call:
    inputs:
      variavel-demo:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a lone-line script
        run: echo "Hello world" ${{ inputs.variavel-demo }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project